// GENERADO por scripts/build-glosario-web.py — NO editar a mano.
// Los textos viven en scripts/glosario-definiciones.py, que es también la fuente
// del Excel que revisa Lister. Una sola fuente: no pueden divergir.
//
// ⚠ ESTADO: BORRADOR SIN VALIDACIÓN MÉDICA. Por eso este glosario NO entra en la
// edición de lanzamiento (ver CON_GLOSARIO_MEDICO en app/edicion.js). El día que
// Lister devuelva el Excel firmado se corrigen los textos acá, se regenera y se
// abre el flag. Publicar una definición médica sin firma es el mismo error que
// publicar una cobertura sin grilla, y pesa más.
//
// Quedan afuera a propósito: los modificadores ("abierto", "por vena") porque
// solo tienen sentido dentro de la fila, y los ambiguos (AC, CA, SENOS, SENO,
// SACO, DETER) porque no sabemos qué significan en esta grilla.

export const MEDICOS = {
  abdomen: { t: "Abdomen", d: "La panza: la zona entre las costillas y la cadera." },
  abdominal: { t: "Abdominal", d: "De la panza." },
  absceso: { t: "Absceso", d: "Una bolsa de pus. Casi siempre hay que drenarla para que cure." },
  afp: { t: "AFP", d: "Una sustancia que se mide en el embarazo y también como señal de alerta de algunos tumores." },
  albumina: { t: "Albumina", d: "La proteína más abundante de la sangre. Si está baja, puede haber un problema en el hígado o en el riñón." },
  alergia: { t: "Alergia", d: "Trata las reacciones exageradas del cuerpo: al polvo, a alimentos, a remedios." },
  amputacion: { t: "Amputación", d: "Sacar un miembro o una parte de él." },
  ana: { t: "ANA", d: "Un análisis que busca si tus defensas están atacando a tu propio cuerpo. Se pide ante sospecha de enfermedades como el lupus." },
  anticuerpo: { t: "Anticuerpo", d: "Igual que el anterior, en singular." },
  anticuerpos: { t: "Anticuerpos", d: "Las defensas que fabrica el cuerpo contra una infección. Si están en el análisis, tu cuerpo se cruzó con eso alguna vez." },
  antigeno: { t: "Antigeno", d: "Un pedacito del microbio en sí. A diferencia de los anticuerpos, encontrarlo quiere decir que el microbio está ahora." },
  antigenos: { t: "Antigenos", d: "Igual que el anterior, en plural." },
  antinucleares: { t: "Antinucleares", d: "Defensas que en vez de atacar a un microbio atacan al propio cuerpo. Se buscan ante sospecha de enfermedades como el lupus." },
  apendicetomia: { t: "Apendicetomía", d: "Sacar el apéndice. Es la operación de la apendicitis." },
  articulaciones: { t: "Articulaciones", d: "Los lugares donde se unen dos huesos y hay movimiento: la rodilla, el hombro, el codo." },
  baar: { t: "BAAR", d: "La prueba que busca la bacteria de la tuberculosis en una muestra." },
  biopsia: { t: "Biopsia", d: "El médico saca una muestra chiquita de tejido para mandarla a analizar. Sirve para saber con certeza qué es algo que se vio en un estudio." },
  blandas: { t: "Blandas", d: "\"Partes blandas\" son los músculos, la grasa y los tejidos que rodean al hueso." },
  calcio: { t: "Calcio", d: "El mineral de los huesos. En sangre se mide porque también hace falta para que funcionen los músculos y los nervios." },
  cardiocirugia: { t: "Cardiocirugía", d: "La cirugía del corazón." },
  cardiologia: { t: "Cardiología", d: "El médico del corazón y la presión." },
  cea: { t: "CEA", d: "Una sustancia que puede subir cuando hay ciertos tumores, sobre todo del intestino. Se usa para seguir un tratamiento." },
  cervical: { t: "Cervical", d: "La parte de la columna que está en el cuello." },
  chlamydia: { t: "Chlamydia", d: "Una bacteria de transmisión sexual. Suele no dar síntomas, y si no se trata puede afectar la fertilidad." },
  ck: { t: "CK", d: "Una sustancia que sube en sangre cuando se dañó un músculo — incluido el del corazón." },
  clavicula: { t: "Clavicula", d: "El hueso fino que va del cuello al hombro. Se quiebra seguido en caídas." },
  colangiografia: { t: "Colangiografia", d: "Un estudio con contraste que mira las vías por donde circula la bilis, para ver si hay una piedra o una obstrucción." },
  colesterol: { t: "Colesterol", d: "Una grasa de la sangre. Demasiado del malo tapa las arterias con los años." },
  coloproctologia: { t: "Coloproctología", d: "Trata el intestino grueso, el recto y el ano. Es a quien se va por hemorroides o fisuras." },
  colporrafia: { t: "Colporrafía", d: "Reparar la pared de la vagina cuando se aflojó, por ejemplo después de varios partos." },
  columna: { t: "Columna", d: "La fila de huesos de la espalda, desde el cuello hasta la cola." },
  complemento: { t: "Complemento", d: "Un grupo de proteínas que ayudan a las defensas a hacer su trabajo. Se miden en enfermedades del sistema inmune." },
  contraste: { t: "Contraste", d: "Un líquido que se toma o se inyecta y hace que ciertas partes del cuerpo se vean mejor en el estudio." },
  cornea: { t: "Cornea", d: "La capa transparente que cubre el ojo por delante." },
  cortisol: { t: "Cortisol", d: "La hormona del estrés. Se mide cuando se sospecha que las glándulas que la fabrican andan mal." },
  coxis: { t: "Coxis", d: "El huesito del final de la columna, el de la cola." },
  craneo: { t: "Craneo", d: "Los huesos de la cabeza, los que protegen el cerebro." },
  cualitativo: { t: "Cualitativo", d: "El resultado viene como un sí o un no: si hay o no hay." },
  cuantitativo: { t: "Cuantitativo", d: "El resultado viene con un número: cuánto hay." },
  cultivo: { t: "Cultivo", d: "Se deja crecer una muestra unos días en el laboratorio, para ver qué bacteria hay y qué antibiótico le gana." },
  dermatologia: { t: "Dermatología", d: "El médico de la piel, el pelo y las uñas." },
  diabetologia: { t: "Diabetología", d: "Se dedica a la diabetes: el control del azúcar en sangre." },
  doppler: { t: "Doppler", d: "Una ecografía que además muestra cómo circula la sangre por dentro de una vena o una arteria." },
  dorsal: { t: "Dorsal", d: "La parte de la columna que está a la altura de las costillas, en el medio de la espalda." },
  drenaje: { t: "Drenaje", d: "Sacar líquido o pus acumulado, con una aguja o un tubito, para que la zona deje de estar hinchada o infectada." },
  duodeno: { t: "Duodeno", d: "La primera parte del intestino, justo después del estómago." },
  ecografia: { t: "Ecografia", d: "Un estudio que mira por dentro con ondas de sonido. No duele, no usa rayos y se puede repetir sin problema." },
  electrocoagulacion: { t: "Electrocoagulación", d: "Cerrar o quemar un tejido con calor, para que deje de sangrar o para sacar una lesión chica." },
  electroforesis: { t: "Electroforesis", d: "Una técnica que separa las proteínas de la sangre para ver si alguna está de más o de menos." },
  endocrinologia: { t: "Endocrinología", d: "Trata las hormonas: tiroides, crecimiento, peso." },
  epstein: { t: "Epstein", d: "\"Epstein-Barr\" es el virus de la mononucleosis, la que llaman enfermedad del beso." },
  escision: { t: "Escisión", d: "Sacar por completo algo del cuerpo: un lunar, un quiste, un bultito." },
  escrotal: { t: "Escrotal", d: "De la bolsa que contiene los testículos." },
  esofago: { t: "Esofago", d: "El tubo que lleva la comida desde la garganta hasta el estómago." },
  esternon: { t: "Esternon", d: "El hueso plano del centro del pecho, donde se enganchan las costillas." },
  extirpacion: { t: "Extirpación", d: "Sacar entero un órgano o una parte del cuerpo." },
  extraccion: { t: "Extracción", d: "Sacar algo del cuerpo: una muestra de sangre, una pieza dental, algo que se clavó." },
  extrano: { t: "Extraño", d: "\"Cuerpo extraño\" es algo de afuera que quedó adentro del cuerpo: una astilla, un vidrio, algo que un chico se tragó." },
  faciales: { t: "Faciales", d: "De la cara." },
  femur: { t: "Femur", d: "El hueso del muslo, el más largo del cuerpo." },
  flebologia: { t: "Flebologia", d: "Se ocupa de las venas: várices, circulación de las piernas." },
  fonoaudiologia: { t: "Fonoaudiología", d: "Trabaja el habla, la voz, la audición y la deglución." },
  fosfatasa: { t: "Fosfatasa", d: "Una sustancia que se mide para estudiar el hígado, la vía biliar o los huesos." },
  frotis: { t: "Frotis", d: "Se extiende una muestra sobre un vidrio para mirarla al microscopio." },
  fsh: { t: "FSH", d: "Una hormona de la fertilidad. Se mide para estudiar por qué no llega un embarazo, o cómo viene la menopausia." },
  gastroenterologia: { t: "Gastroenterología", d: "El médico del estómago, el intestino y el hígado." },
  geriatria: { t: "Geriatría", d: "El médico especializado en personas mayores." },
  germenes: { t: "Germenes", d: "Los microbios: bacterias, hongos o virus que pueden causar una infección." },
  ginecologia: { t: "Ginecología", d: "El médico de la salud de la mujer." },
  glandula: { t: "Glándula", d: "Un órgano chico que fabrica algo que el cuerpo necesita: hormonas, saliva, sudor." },
  glucosa: { t: "Glucosa", d: "El azúcar de la sangre. Es lo que se mide para controlar o detectar diabetes." },
  got: { t: "GOT", d: "Una sustancia del hígado. Si está alta en sangre, el hígado puede estar inflamado." },
  gpt: { t: "GPT", d: "Otra sustancia del hígado, que se mide junto con la anterior para ver cómo está funcionando." },
  hcg: { t: "HCG", d: "La hormona del embarazo. Es el análisis que confirma si estás embarazada." },
  hdl: { t: "HDL", d: "El colesterol bueno: el que ayuda a limpiar las arterias." },
  hematologia: { t: "Hematologia", d: "Se ocupa de la sangre: anemias, coagulación, defensas." },
  hemoglobina: { t: "Hemoglobina", d: "La parte de la sangre que lleva el oxígeno. Si está baja, es anemia." },
  hepatitis: { t: "Hepatitis", d: "Una inflamación del hígado, casi siempre por un virus. Hay varios tipos y se contagian distinto." },
  hernia: { t: "Hernia", d: "Cuando una parte del interior empuja y sale por un punto débil de la pared del cuerpo. Se ve como un bulto." },
  herniorrafia: { t: "Herniorrafía", d: "La operación de la hernia: se vuelve a cerrar la pared que se abrió y dejó salir el bulto." },
  histerectomia: { t: "Histerectomía", d: "Sacar el útero." },
  hiv: { t: "HIV", d: "El virus que causa el sida. El análisis dice si la persona lo tiene." },
  hormona: { t: "Hormona", d: "Un mensajero que fabrica una glándula y viaja por la sangre para dar una orden a otro órgano." },
  humero: { t: "Humero", d: "El hueso del brazo, entre el hombro y el codo." },
  iga: { t: "IGA", d: "Otra defensa del cuerpo, presente sobre todo en la saliva, las lágrimas y el intestino." },
  ige: { t: "IGE", d: "La defensa que se activa en las alergias. Se mide cuando se sospecha que algo te da alergia." },
  igg: { t: "IGG", d: "Un tipo de defensa que el cuerpo fabrica y deja guardada. Si aparece, quiere decir que ya tuviste contacto con esa infección, aunque haya sido hace años." },
  igm: { t: "IGM", d: "Un tipo de defensa que el cuerpo fabrica al principio de una infección. Si aparece, la infección suele ser reciente." },
  iliacas: { t: "Iliacas", d: "Las alas anchas del hueso de la cadera." },
  incision: { t: "Incisión", d: "El corte que hace el médico para llegar a lo que tiene que tratar." },
  infectologia: { t: "Infectología", d: "Trata las infecciones difíciles o que no ceden." },
  inguinal: { t: "Inguinal", d: "De la ingle, donde termina la panza y empieza la pierna." },
  inmunoglobulinas: { t: "Inmunoglobulinas", d: "El nombre técnico de las defensas del cuerpo. Se miden para ver si las defensas están altas, bajas o desbalanceadas." },
  interconsulta: { t: "Interconsulta", d: "Cuando tu médico pide la opinión de otro especialista sobre tu caso." },
  intestinal: { t: "Intestinal", d: "Del intestino." },
  lagrimal: { t: "Lagrimal", d: "El conductito por donde bajan las lágrimas desde el ojo hasta la nariz." },
  laparotomia: { t: "Laparotomía", d: "Abrir el abdomen para operar, o para ver qué está pasando adentro cuando los estudios no alcanzan." },
  latex: { t: "Latex", d: "Una técnica rápida de laboratorio que usa partículas que se pegan entre sí cuando encuentran lo que buscan." },
  lcr: { t: "LCR", d: "El líquido que rodea al cerebro y a la médula. Se saca con una punción en la espalda y se analiza cuando se sospecha una infección o inflamación ahí." },
  ldh: { t: "LDH", d: "Una sustancia que sube cuando hay daño en algún tejido del cuerpo. Es una pista general, no dice dónde." },
  ldl: { t: "LDL", d: "El colesterol malo: el que se va pegando a las arterias." },
  legionella: { t: "Legionella", d: "Una bacteria que vive en el agua de tanques y aires acondicionados y puede causar neumonía." },
  legrado: { t: "Legrado", d: "Raspar el interior del útero — por ejemplo después de una pérdida, o para estudiar un sangrado que no para." },
  lesion: { t: "Lesión", d: "Cualquier cosa que no debería estar ahí o que está dañada: un bultito, una mancha, una zona lastimada." },
  lh: { t: "LH", d: "Otra hormona de la fertilidad: es la que dispara la ovulación." },
  linfadenectomia: { t: "Linfadenectomía", d: "Sacar ganglios, casi siempre para estudiar si un tumor se extendió." },
  lumbar: { t: "Lumbar", d: "La parte baja de la espalda, donde se siente el dolor de riñones." },
  mastoides: { t: "Mastoides", d: "El hueso que está justo detrás de la oreja. Se estudia cuando hay infecciones de oído que no ceden." },
  mastologia: { t: "Mastología", d: "Se dedica a las mamas: controles, bultos, prevención." },
  maxilar: { t: "Maxilar", d: "El hueso de la mandíbula." },
  maxilares: { t: "Maxilares", d: "Los huesos de la mandíbula, arriba y abajo." },
  microbianos: { t: "Microbianos", d: "De los microbios." },
  microbiologico: { t: "Microbiologico", d: "El análisis que busca bacterias, hongos o parásitos en una muestra." },
  miembro: { t: "Miembro", d: "Un brazo o una pierna." },
  miembros: { t: "Miembros", d: "Los brazos y las piernas." },
  monitoreo: { t: "Monitoreo", d: "Seguir un valor durante un tiempo en vez de medirlo una sola vez." },
  mycoplasma: { t: "Mycoplasma", d: "Una bacteria que causa neumonías e infecciones respiratorias, sobre todo en gente joven." },
  nasal: { t: "Nasal", d: "De la nariz." },
  nefrectomia: { t: "Nefrectomía", d: "Sacar un riñón, entero o una parte." },
  nefrologia: { t: "Nefrología", d: "El médico del riñón." },
  neumologia: { t: "Neumología", d: "El médico del pulmón y la respiración." },
  neurocirugia: { t: "Neurocirugía", d: "La cirugía del cerebro, la columna y los nervios." },
  neurologia: { t: "Neurología", d: "Trata el cerebro y los nervios: dolores de cabeza, mareos, convulsiones." },
  obstetricia: { t: "Obstetricia", d: "Acompaña el embarazo y el parto." },
  oftalmologia: { t: "Oftalmología", d: "El médico de los ojos." },
  oncologia: { t: "Oncología", d: "Trata el cáncer." },
  ooforectomia: { t: "Ooforectomía", d: "Sacar un ovario." },
  orbitas: { t: "Orbitas", d: "Los huecos del cráneo donde van los ojos." },
  otorrinolaringologia: { t: "Otorrinolaringología", d: "El médico del oído, la nariz y la garganta." },
  paladar: { t: "Paladar", d: "El techo de la boca." },
  paranasales: { t: "Paranasales", d: "Los huecos con aire que están alrededor de la nariz. Son los que se tapan e inflaman con la sinusitis." },
  pediatria: { t: "Pediatría", d: "El médico de los chicos." },
  pelvis: { t: "Pelvis", d: "La parte baja del tronco, donde están la vejiga, el útero o la próstata y la parte final del intestino." },
  peritonitis: { t: "Peritonitis", d: "Una infección grave dentro de la panza. Es una urgencia." },
  pielografia: { t: "Pielografia", d: "Un estudio con contraste que mira los riñones y las vías por donde baja la orina." },
  prostatica: { t: "Prostatica", d: "De la próstata, la glándula que tienen los hombres debajo de la vejiga." },
  proteina: { t: "Proteina", d: "Igual que el anterior, en singular." },
  proteinas: { t: "Proteinas", d: "Los ladrillos del cuerpo. En un análisis, sus valores hablan de cómo andan el hígado, el riñón y la alimentación." },
  psiquiatria: { t: "Psiquiatría", d: "Trata la salud mental y puede indicar medicación." },
  ptgo: { t: "PTGO", d: "Tomás un líquido dulce y te miden el azúcar en sangre varias veces, para ver cómo lo procesa tu cuerpo. Sirve para detectar diabetes." },
  puncion: { t: "Punción", d: "Entrar con una aguja fina para sacar líquido o una muestra, sin necesidad de abrir." },
  quiste: { t: "Quiste", d: "Una bolsita con líquido adentro. La mayoría son inofensivos, pero a veces se sacan." },
  reactiva: { t: "Reactiva", d: "\"Proteína C reactiva\" sube cuando hay inflamación en algún lado del cuerpo. No dice dónde: dice que la hay." },
  reduccion: { t: "Reducción", d: "Acomodar un hueso quebrado o una articulación salida, para devolverlos a su lugar." },
  renal: { t: "Renal", d: "Del riñón." },
  reseccion: { t: "Resección", d: "Cortar y sacar una parte de un órgano, dejando el resto en su lugar." },
  reumatoideo: { t: "Reumatoideo", d: "\"Factor reumatoideo\" es una señal en sangre que aparece en la artritis reumatoidea." },
  reumatologia: { t: "Reumatología", d: "Se ocupa de las articulaciones y los dolores crónicos: artritis, artrosis." },
  rmn: { t: "RMN", d: "Resonancia magnética. Mira por dentro del cuerpo con imanes, sin rayos. Se usa sobre todo para articulaciones, columna y cabeza." },
  sacro: { t: "Sacro", d: "El hueso ancho y plano del final de la columna, arriba de la cola." },
  sacroiliacas: { t: "Sacroiliacas", d: "Las dos uniones entre el hueso del final de la columna y la cadera." },
  secrecion: { t: "Secrecion", d: "El líquido que produce una parte del cuerpo — por ejemplo de la garganta, del oído o de una herida— y que se manda a analizar." },
  sinusotomia: { t: "Sinusotomía", d: "Abrir un seno de la cara para drenarlo, cuando la sinusitis no cede con remedios." },
  streptococcus: { t: "Streptococcus", d: "Un grupo de bacterias muy común. Son las de la angina de garganta, entre otras." },
  subcutaneo: { t: "Subcutáneo", d: "Debajo de la piel." },
  suero: { t: "Suero", d: "La parte líquida de la sangre, sin las células. Es sobre lo que se hacen muchos análisis." },
  sutura: { t: "Sutura", d: "Coser una herida para que cierre. Son los puntos." },
  tac: { t: "TAC", d: "Tomografía. Saca muchas radiografías seguidas y arma con ellas una imagen del interior, mucho más detallada que una radiografía común." },
  tcms: { t: "TCMS", d: "Una tomografía más moderna y rápida, que saca varios cortes a la vez. Se usa cuando hace falta más detalle." },
  temporales: { t: "Temporales", d: "De los costados de la cabeza, a la altura de las sienes." },
  testicular: { t: "Testicular", d: "Del testículo." },
  tincion: { t: "Tincion", d: "Se pinta la muestra con un colorante para poder ver al microscopio lo que a simple vista no se distingue." },
  tiroides: { t: "Tiroides", d: "Una glándula del cuello que regula el ritmo del cuerpo: el peso, el humor, la energía." },
  tolerancia: { t: "Tolerancia", d: "Se mide cómo reacciona tu cuerpo frente a algo que se te da a propósito — por ejemplo azúcar — para ver si lo procesa bien." },
  torax: { t: "Torax", d: "El pecho: la zona de las costillas, donde están los pulmones y el corazón." },
  toxoplasma: { t: "Toxoplasma", d: "Un parásito que se contagia por carne mal cocida o por heces de gato. Importa sobre todo en el embarazo." },
  tp: { t: "TP", d: "Mide cuánto tarda tu sangre en coagular. Se controla sobre todo en quienes toman anticoagulantes." },
  transfusion: { t: "Transfusión", d: "Pasarle a la persona sangre de un donante." },
  traumatismo: { t: "Traumatismo", d: "Un golpe o una lesión causada desde afuera: una caída, un accidente." },
  traumatologia: { t: "Traumatología", d: "El médico de los huesos, las fracturas y los golpes." },
  treponema: { t: "Treponema", d: "La bacteria que causa la sífilis." },
  tsh: { t: "TSH", d: "La hormona que le ordena trabajar a la tiroides. Se mide para saber si la tiroides anda acelerada o lenta." },
  ttpa: { t: "TTPA", d: "Otra medida de cuánto tarda la sangre en coagular, que mira una parte distinta del proceso." },
  tumor: { t: "Tumor", d: "Un bulto de células que crecieron de más. No todos son cáncer: muchos son benignos." },
  urea: { t: "Urea", d: "Un desecho que los riñones tienen que eliminar. Si está alta en sangre, los riñones pueden no estar filtrando bien." },
  uretral: { t: "Uretral", d: "Del conducto por donde sale la orina." },
  urinario: { t: "Urinario", d: "Del sistema que fabrica y elimina la orina: riñones, vejiga y sus conductos." },
  urologia: { t: "Urología", d: "El médico de las vías urinarias y de la salud del hombre." },
  uterina: { t: "Uterina", d: "Del útero." },
  uterino: { t: "Uterino", d: "Del útero, donde crece el bebé." },
  vaginal: { t: "Vaginal", d: "De la vagina." },
  vdrl: { t: "VDRL", d: "El análisis de sangre que se usa para detectar sífilis." },
  vesical: { t: "Vesical", d: "De la vejiga, donde se junta la orina." },
  videolaparoscopia: { t: "Videolaparoscopía", d: "Operar por agujeritos chicos, con una cámara que le muestra al cirujano lo que hace. Se recupera más rápido que abriendo." },
  virus: { t: "Virus", d: "Un microbio muy chico que se mete en las células para multiplicarse. Los antibióticos no le hacen nada." },
};
