# -*- coding: utf-8 -*-
# Borradores de definición, en idioma de familia. Regla del proyecto: si una
# definición necesita otra palabra difícil para explicarse, está mal escrita.
# Estado: D = definición propuesta · M = modificador (se explica en la ficha,
# no como palabra suelta) · C = hay que confirmar con Lister qué significa acá.
DEFS = {
# ── siglas ──────────────────────────────────────────────────────────────
'IGG':('D','Un tipo de defensa que el cuerpo fabrica y deja guardada. Si aparece, quiere decir que ya tuviste contacto con esa infección, aunque haya sido hace años.'),
'IGM':('D','Un tipo de defensa que el cuerpo fabrica al principio de una infección. Si aparece, la infección suele ser reciente.'),
'IGA':('D','Otra defensa del cuerpo, presente sobre todo en la saliva, las lágrimas y el intestino.'),
'IGE':('D','La defensa que se activa en las alergias. Se mide cuando se sospecha que algo te da alergia.'),
'RMN':('D','Resonancia magnética. Mira por dentro del cuerpo con imanes, sin rayos. Se usa sobre todo para articulaciones, columna y cabeza.'),
'TAC':('D','Tomografía. Saca muchas radiografías seguidas y arma con ellas una imagen del interior, mucho más detallada que una radiografía común.'),
'TCMS':('D','Una tomografía más moderna y rápida, que saca varios cortes a la vez. Se usa cuando hace falta más detalle.'),
'BAAR':('D','La prueba que busca la bacteria de la tuberculosis en una muestra.'),
'PTGO':('D','Tomás un líquido dulce y te miden el azúcar en sangre varias veces, para ver cómo lo procesa tu cuerpo. Sirve para detectar diabetes.'),
'LCR':('D','El líquido que rodea al cerebro y a la médula. Se saca con una punción en la espalda y se analiza cuando se sospecha una infección o inflamación ahí.'),
'ANA':('D','Un análisis que busca si tus defensas están atacando a tu propio cuerpo. Se pide ante sospecha de enfermedades como el lupus.'),
'CK':('D','Una sustancia que sube en sangre cuando se dañó un músculo — incluido el del corazón.'),
'VDRL':('D','El análisis de sangre que se usa para detectar sífilis.'),
'HCG':('D','La hormona del embarazo. Es el análisis que confirma si estás embarazada.'),
'HIV':('D','El virus que causa el sida. El análisis dice si la persona lo tiene.'),
'TSH':('D','La hormona que le ordena trabajar a la tiroides. Se mide para saber si la tiroides anda acelerada o lenta.'),
'AFP':('D','Una sustancia que se mide en el embarazo y también como señal de alerta de algunos tumores.'),
'CEA':('D','Una sustancia que puede subir cuando hay ciertos tumores, sobre todo del intestino. Se usa para seguir un tratamiento.'),
'FSH':('D','Una hormona de la fertilidad. Se mide para estudiar por qué no llega un embarazo, o cómo viene la menopausia.'),
'LH':('D','Otra hormona de la fertilidad: es la que dispara la ovulación.'),
'GOT':('D','Una sustancia del hígado. Si está alta en sangre, el hígado puede estar inflamado.'),
'GPT':('D','Otra sustancia del hígado, que se mide junto con la anterior para ver cómo está funcionando.'),
'HDL':('D','El colesterol bueno: el que ayuda a limpiar las arterias.'),
'LDL':('D','El colesterol malo: el que se va pegando a las arterias.'),
'LDH':('D','Una sustancia que sube cuando hay daño en algún tejido del cuerpo. Es una pista general, no dice dónde.'),
'TP':('D','Mide cuánto tarda tu sangre en coagular. Se controla sobre todo en quienes toman anticoagulantes.'),
'TTPA':('D','Otra medida de cuánto tarda la sangre en coagular, que mira una parte distinta del proceso.'),
'AC':('C','En la grilla parece ser la abreviatura de "anticuerpos". ⚠ Confirmar que siempre significa eso antes de publicar nada.'),
'CA':('C','Parece ser un marcador tumoral (CA-125, CA-19.9). ⚠ Confirmar cuál es en cada fila.'),
'DETER':('C','Aparece cortado: es "determinación". ⚠ No es un término para definir — es un nombre mal cargado en la grilla, conviene corregirlo en el origen.'),
# ── procedimientos ──────────────────────────────────────────────────────
'BIOPSIA':('D','El médico saca una muestra chiquita de tejido para mandarla a analizar. Sirve para saber con certeza qué es algo que se vio en un estudio.'),
'DRENAJE':('D','Sacar líquido o pus acumulado, con una aguja o un tubito, para que la zona deje de estar hinchada o infectada.'),
'ESCISIÓN':('D','Sacar por completo algo del cuerpo: un lunar, un quiste, un bultito.'),
'SUTURA':('D','Coser una herida para que cierre. Son los puntos.'),
'INCISIÓN':('D','El corte que hace el médico para llegar a lo que tiene que tratar.'),
'PUNCIÓN':('D','Entrar con una aguja fina para sacar líquido o una muestra, sin necesidad de abrir.'),
'EXTRACCIÓN':('D','Sacar algo del cuerpo: una muestra de sangre, una pieza dental, algo que se clavó.'),
'EXTIRPACIÓN':('D','Sacar entero un órgano o una parte del cuerpo.'),
'RESECCIÓN':('D','Cortar y sacar una parte de un órgano, dejando el resto en su lugar.'),
'VIDEOLAPAROSCOPÍA':('D','Operar por agujeritos chicos, con una cámara que le muestra al cirujano lo que hace. Se recupera más rápido que abriendo.'),
'NEFRECTOMÍA':('D','Sacar un riñón, entero o una parte.'),
'TRANSFUSIÓN':('D','Pasarle a la persona sangre de un donante.'),
'AMPUTACIÓN':('D','Sacar un miembro o una parte de él.'),
'APENDICETOMÍA':('D','Sacar el apéndice. Es la operación de la apendicitis.'),
'COLPORRAFÍA':('D','Reparar la pared de la vagina cuando se aflojó, por ejemplo después de varios partos.'),
'ELECTROCOAGULACIÓN':('D','Cerrar o quemar un tejido con calor, para que deje de sangrar o para sacar una lesión chica.'),
'HERNIORRAFÍA':('D','La operación de la hernia: se vuelve a cerrar la pared que se abrió y dejó salir el bulto.'),
'HISTERECTOMÍA':('D','Sacar el útero.'),
'OOFORECTOMÍA':('D','Sacar un ovario.'),
'LAPAROTOMÍA':('D','Abrir el abdomen para operar, o para ver qué está pasando adentro cuando los estudios no alcanzan.'),
'LEGRADO':('D','Raspar el interior del útero — por ejemplo después de una pérdida, o para estudiar un sangrado que no para.'),
'LINFADENECTOMÍA':('D','Sacar ganglios, casi siempre para estudiar si un tumor se extendió.'),
'SINUSOTOMÍA':('D','Abrir un seno de la cara para drenarlo, cuando la sinusitis no cede con remedios.'),
'INTERCONSULTA':('D','Cuando tu médico pide la opinión de otro especialista sobre tu caso.'),
'REDUCCIÓN':('D','Acomodar un hueso quebrado o una articulación salida, para devolverlos a su lugar.'),
'SUBCUTÁNEO':('D','Debajo de la piel.'),
'QUIRÚRGICO':('M','Quiere decir "de cirugía". Se entiende en la fila; no hace falta definirlo aparte.'),
'QUIRÚRGICA':('M','Igual que el anterior.'),
'RADICAL':('M','En cirugía quiere decir que se saca todo, no solo la parte enferma. Conviene decirlo en la ficha.'),
'ABIERTO':('M','Se opone a "por laparoscopía": la operación se hace abriendo. Va explicado en la ficha.'),
'CIERRE':('M','Parte del nombre de la operación. Se explica en la ficha.'),
'DIAGNÓSTICA':('M','Quiere decir que el procedimiento se hace para averiguar qué pasa, no para tratar.'),
'EXPLORACIÓN':('M','Mirar una zona para ver qué hay. Se explica en la ficha.'),
'EXPLORADORA':('M','Igual que el anterior.'),
'OPERATORIA':('M','Parte del nombre. Se explica en la ficha.'),
'DESCUBIERTA':('M','Parte del nombre de la técnica. ⚠ Confirmar con Lister a qué se refiere.'),
'INSTALACIÓN':('M','Colocar algo: una sonda, un catéter, una prótesis. Se explica en la ficha.'),
'PROCEDIMIENTOS':('M','Palabra general del tarifario, no un término médico.'),
# ── estudios ────────────────────────────────────────────────────────────
'ECOGRAFIA':('D','Un estudio que mira por dentro con ondas de sonido. No duele, no usa rayos y se puede repetir sin problema.'),
'CULTIVO':('D','Se deja crecer una muestra unos días en el laboratorio, para ver qué bacteria hay y qué antibiótico le gana.'),
'DOPPLER':('D','Una ecografía que además muestra cómo circula la sangre por dentro de una vena o una arteria.'),
'TINCION':('D','Se pinta la muestra con un colorante para poder ver al microscopio lo que a simple vista no se distingue.'),
'FROTIS':('D','Se extiende una muestra sobre un vidrio para mirarla al microscopio.'),
'ELECTROFORESIS':('D','Una técnica que separa las proteínas de la sangre para ver si alguna está de más o de menos.'),
'MICROBIOLOGICO':('D','El análisis que busca bacterias, hongos o parásitos en una muestra.'),
'COLANGIOGRAFIA':('D','Un estudio con contraste que mira las vías por donde circula la bilis, para ver si hay una piedra o una obstrucción.'),
'PIELOGRAFIA':('D','Un estudio con contraste que mira los riñones y las vías por donde baja la orina.'),
'CONTRASTE':('D','Un líquido que se toma o se inyecta y hace que ciertas partes del cuerpo se vean mejor en el estudio.'),
'TOLERANCIA':('D','Se mide cómo reacciona tu cuerpo frente a algo que se te da a propósito — por ejemplo azúcar — para ver si lo procesa bien.'),
'MONITOREO':('D','Seguir un valor durante un tiempo en vez de medirlo una sola vez.'),
'LATEX':('D','Una técnica rápida de laboratorio que usa partículas que se pegan entre sí cuando encuentran lo que buscan.'),
'REACCION':('M','Parte del nombre de la técnica de laboratorio. Se explica en la ficha.'),
'CUANTITATIVO':('D','El resultado viene con un número: cuánto hay.'),
'CUALITATIVO':('D','El resultado viene como un sí o un no: si hay o no hay.'),
'OSEA':('M','Quiere decir "del hueso".'),
'FETAL':('M','Quiere decir "del bebé en la panza".'),
'ORAL':('M','Por la boca.'),
'VENOSA':('M','Por la vena.'),
'VENOSO':('M','Por la vena.'),
# ── anatomía ────────────────────────────────────────────────────────────
'COLUMNA':('D','La fila de huesos de la espalda, desde el cuello hasta la cola.'),
'CERVICAL':('D','La parte de la columna que está en el cuello.'),
'DORSAL':('D','La parte de la columna que está a la altura de las costillas, en el medio de la espalda.'),
'LUMBAR':('D','La parte baja de la espalda, donde se siente el dolor de riñones.'),
'SACRO':('D','El hueso ancho y plano del final de la columna, arriba de la cola.'),
'COXIS':('D','El huesito del final de la columna, el de la cola.'),
'SACROILIACAS':('D','Las dos uniones entre el hueso del final de la columna y la cadera.'),
'ILIACAS':('D','Las alas anchas del hueso de la cadera.'),
'HUMERO':('D','El hueso del brazo, entre el hombro y el codo.'),
'FEMUR':('D','El hueso del muslo, el más largo del cuerpo.'),
'CLAVICULA':('D','El hueso fino que va del cuello al hombro. Se quiebra seguido en caídas.'),
'ESTERNON':('D','El hueso plano del centro del pecho, donde se enganchan las costillas.'),
'CRANEO':('D','Los huesos de la cabeza, los que protegen el cerebro.'),
'MASTOIDES':('D','El hueso que está justo detrás de la oreja. Se estudia cuando hay infecciones de oído que no ceden.'),
'ORBITAS':('D','Los huecos del cráneo donde van los ojos.'),
'MAXILAR':('D','El hueso de la mandíbula.'),
'MAXILARES':('D','Los huesos de la mandíbula, arriba y abajo.'),
'PARANASALES':('D','Los huecos con aire que están alrededor de la nariz. Son los que se tapan e inflaman con la sinusitis.'),
'SENOS':('C','En esta grilla puede querer decir dos cosas muy distintas: los huecos de la cara (sinusitis) o las mamas. ⚠ Confirmar fila por fila.'),
'SENO':('C','Igual que el anterior. ⚠ Confirmar.'),
'LAGRIMAL':('D','El conductito por donde bajan las lágrimas desde el ojo hasta la nariz.'),
'CORNEA':('D','La capa transparente que cubre el ojo por delante.'),
'PALADAR':('D','El techo de la boca.'),
'ESOFAGO':('D','El tubo que lleva la comida desde la garganta hasta el estómago.'),
'DUODENO':('D','La primera parte del intestino, justo después del estómago.'),
'TIROIDES':('D','Una glándula del cuello que regula el ritmo del cuerpo: el peso, el humor, la energía.'),
'GLÁNDULA':('D','Un órgano chico que fabrica algo que el cuerpo necesita: hormonas, saliva, sudor.'),
'PELVIS':('D','La parte baja del tronco, donde están la vejiga, el útero o la próstata y la parte final del intestino.'),
'ABDOMEN':('D','La panza: la zona entre las costillas y la cadera.'),
'ABDOMINAL':('D','De la panza.'),
'TORAX':('D','El pecho: la zona de las costillas, donde están los pulmones y el corazón.'),
'INGUINAL':('D','De la ingle, donde termina la panza y empieza la pierna.'),
'ESCROTAL':('D','De la bolsa que contiene los testículos.'),
'PROSTATICA':('D','De la próstata, la glándula que tienen los hombres debajo de la vejiga.'),
'URETRAL':('D','Del conducto por donde sale la orina.'),
'VESICAL':('D','De la vejiga, donde se junta la orina.'),
'URINARIO':('D','Del sistema que fabrica y elimina la orina: riñones, vejiga y sus conductos.'),
'RENAL':('D','Del riñón.'),
'UTERINO':('D','Del útero, donde crece el bebé.'),
'UTERINA':('D','Del útero.'),
'VAGINAL':('D','De la vagina.'),
'TESTICULAR':('D','Del testículo.'),
'INTESTINAL':('D','Del intestino.'),
'NASAL':('D','De la nariz.'),
'FACIALES':('D','De la cara.'),
'TEMPORALES':('D','De los costados de la cabeza, a la altura de las sienes.'),
'ARTICULACIONES':('D','Los lugares donde se unen dos huesos y hay movimiento: la rodilla, el hombro, el codo.'),
'BLANDAS':('D','"Partes blandas" son los músculos, la grasa y los tejidos que rodean al hueso.'),
'MIEMBRO':('D','Un brazo o una pierna.'),
'MIEMBROS':('D','Los brazos y las piernas.'),
'SACO':('C','Puede referirse a varias estructuras según la fila (saco lagrimal, saco herniario). ⚠ Confirmar.'),
'VÍA':('M','El camino por donde pasa algo: la vía urinaria, la vía biliar. Se entiende en la ficha.'),
# ── sustancias ──────────────────────────────────────────────────────────
'ANTICUERPOS':('D','Las defensas que fabrica el cuerpo contra una infección. Si están en el análisis, tu cuerpo se cruzó con eso alguna vez.'),
'ANTICUERPO':('D','Igual que el anterior, en singular.'),
'ANTIGENO':('D','Un pedacito del microbio en sí. A diferencia de los anticuerpos, encontrarlo quiere decir que el microbio está ahora.'),
'ANTIGENOS':('D','Igual que el anterior, en plural.'),
'ANTINUCLEARES':('D','Defensas que en vez de atacar a un microbio atacan al propio cuerpo. Se buscan ante sospecha de enfermedades como el lupus.'),
'INMUNOGLOBULINAS':('D','El nombre técnico de las defensas del cuerpo. Se miden para ver si las defensas están altas, bajas o desbalanceadas.'),
'COMPLEMENTO':('D','Un grupo de proteínas que ayudan a las defensas a hacer su trabajo. Se miden en enfermedades del sistema inmune.'),
'REUMATOIDEO':('D','"Factor reumatoideo" es una señal en sangre que aparece en la artritis reumatoidea.'),
'REACTIVA':('D','"Proteína C reactiva" sube cuando hay inflamación en algún lado del cuerpo. No dice dónde: dice que la hay.'),
'GLUCOSA':('D','El azúcar de la sangre. Es lo que se mide para controlar o detectar diabetes.'),
'HEMOGLOBINA':('D','La parte de la sangre que lleva el oxígeno. Si está baja, es anemia.'),
'COLESTEROL':('D','Una grasa de la sangre. Demasiado del malo tapa las arterias con los años.'),
'UREA':('D','Un desecho que los riñones tienen que eliminar. Si está alta en sangre, los riñones pueden no estar filtrando bien.'),
'CORTISOL':('D','La hormona del estrés. Se mide cuando se sospecha que las glándulas que la fabrican andan mal.'),
'ALBUMINA':('D','La proteína más abundante de la sangre. Si está baja, puede haber un problema en el hígado o en el riñón.'),
'FOSFATASA':('D','Una sustancia que se mide para estudiar el hígado, la vía biliar o los huesos.'),
'CALCIO':('D','El mineral de los huesos. En sangre se mide porque también hace falta para que funcionen los músculos y los nervios.'),
'SUERO':('D','La parte líquida de la sangre, sin las células. Es sobre lo que se hacen muchos análisis.'),
'SECRECION':('D','El líquido que produce una parte del cuerpo — por ejemplo de la garganta, del oído o de una herida— y que se manda a analizar.'),
'GERMENES':('D','Los microbios: bacterias, hongos o virus que pueden causar una infección.'),
'MICROBIANOS':('D','De los microbios.'),
'BIOLOGICOS':('M','Quiere decir "del cuerpo": sangre, orina, líquidos. Se entiende en la ficha.'),
'HORMONA':('D','Un mensajero que fabrica una glándula y viaja por la sangre para dar una orden a otro órgano.'),
'PROTEINAS':('D','Los ladrillos del cuerpo. En un análisis, sus valores hablan de cómo andan el hígado, el riñón y la alimentación.'),
'PROTEINA':('D','Igual que el anterior, en singular.'),
'ACIDO':('M','Parte del nombre de la sustancia que se mide (ácido úrico, ácido fólico). Se explica en la ficha.'),
'FACTOR':('M','Parte del nombre del análisis. Se explica en la ficha.'),
'ALFA':('M','Parte del nombre de la sustancia. Se explica en la ficha.'),
'BETA':('M','Parte del nombre de la sustancia. Se explica en la ficha.'),
'ESPECIFICO':('M','Quiere decir que el análisis busca una sola cosa concreta.'),
# ── organismos ──────────────────────────────────────────────────────────
'HEPATITIS':('D','Una inflamación del hígado, casi siempre por un virus. Hay varios tipos y se contagian distinto.'),
'VIRUS':('D','Un microbio muy chico que se mete en las células para multiplicarse. Los antibióticos no le hacen nada.'),
'CHLAMYDIA':('D','Una bacteria de transmisión sexual. Suele no dar síntomas, y si no se trata puede afectar la fertilidad.'),
'TRACHOMATIS':('M','Es el apellido de la clamidia. Va junto con ella.'),
'MYCOPLASMA':('D','Una bacteria que causa neumonías e infecciones respiratorias, sobre todo en gente joven.'),
'PNEUMONIAE':('M','Es el apellido de la bacteria, e indica que ataca el pulmón.'),
'LEGIONELLA':('D','Una bacteria que vive en el agua de tanques y aires acondicionados y puede causar neumonía.'),
'STREPTOCOCCUS':('D','Un grupo de bacterias muy común. Son las de la angina de garganta, entre otras.'),
'TREPONEMA':('D','La bacteria que causa la sífilis.'),
'PALLIDIUM':('M','Es el apellido de esa bacteria. Va junto con ella.'),
'TOXOPLASMA':('D','Un parásito que se contagia por carne mal cocida o por heces de gato. Importa sobre todo en el embarazo.'),
'GONDII':('M','Es el apellido del toxoplasma. Va junto con él.'),
'EPSTEIN':('D','"Epstein-Barr" es el virus de la mononucleosis, la que llaman enfermedad del beso.'),
'PERITONITIS':('D','Una infección grave dentro de la panza. Es una urgencia.'),
# ── condiciones ─────────────────────────────────────────────────────────
'LESIÓN':('D','Cualquier cosa que no debería estar ahí o que está dañada: un bultito, una mancha, una zona lastimada.'),
'ABSCESO':('D','Una bolsa de pus. Casi siempre hay que drenarla para que cure.'),
'QUISTE':('D','Una bolsita con líquido adentro. La mayoría son inofensivos, pero a veces se sacan.'),
'TUMOR':('D','Un bulto de células que crecieron de más. No todos son cáncer: muchos son benignos.'),
'HERNIA':('D','Cuando una parte del interior empuja y sale por un punto débil de la pared del cuerpo. Se ve como un bulto.'),
'TRAUMATISMO':('D','Un golpe o una lesión causada desde afuera: una caída, un accidente.'),
'EXTRAÑO':('D','"Cuerpo extraño" es algo de afuera que quedó adentro del cuerpo: una astilla, un vidrio, algo que un chico se tragó.'),
'COMPLEJIDAD':('M','Palabra del tarifario que clasifica qué tan compleja es la práctica, no un término médico.'),
}
ESPECIALIDADES = {
'ALERGIA':'Trata las reacciones exageradas del cuerpo: al polvo, a alimentos, a remedios.',
'CARDIOLOGÍA':'El médico del corazón y la presión.',
'CARDIOCIRUGÍA':'La cirugía del corazón.',
'COLOPROCTOLOGÍA':'Trata el intestino grueso, el recto y el ano. Es a quien se va por hemorroides o fisuras.',
'DERMATOLOGÍA':'El médico de la piel, el pelo y las uñas.',
'DIABETOLOGÍA':'Se dedica a la diabetes: el control del azúcar en sangre.',
'ENDOCRINOLOGÍA':'Trata las hormonas: tiroides, crecimiento, peso.',
'FLEBOLOGIA':'Se ocupa de las venas: várices, circulación de las piernas.',
'FONOAUDIOLOGÍA':'Trabaja el habla, la voz, la audición y la deglución.',
'GASTROENTEROLOGÍA':'El médico del estómago, el intestino y el hígado.',
'GERIATRÍA':'El médico especializado en personas mayores.',
'GINECOLOGÍA':'El médico de la salud de la mujer.',
'HEMATOLOGIA':'Se ocupa de la sangre: anemias, coagulación, defensas.',
'INFECTOLOGÍA':'Trata las infecciones difíciles o que no ceden.',
'MASTOLOGÍA':'Se dedica a las mamas: controles, bultos, prevención.',
'NEFROLOGÍA':'El médico del riñón.',
'NEUMOLOGÍA':'El médico del pulmón y la respiración.',
'NEUROLOGÍA':'Trata el cerebro y los nervios: dolores de cabeza, mareos, convulsiones.',
'NEUROCIRUGÍA':'La cirugía del cerebro, la columna y los nervios.',
'OBSTETRICIA':'Acompaña el embarazo y el parto.',
'OFTALMOLOGÍA':'El médico de los ojos.',
'ONCOLOGÍA':'Trata el cáncer.',
'OTORRINOLARINGOLOGÍA':'El médico del oído, la nariz y la garganta.',
'PEDIATRÍA':'El médico de los chicos.',
'PSIQUIATRÍA':'Trata la salud mental y puede indicar medicación.',
'REUMATOLOGÍA':'Se ocupa de las articulaciones y los dolores crónicos: artritis, artrosis.',
'TRAUMATOLOGÍA':'El médico de los huesos, las fracturas y los golpes.',
'UROLOGÍA':'El médico de las vías urinarias y de la salud del hombre.',
}
for k,v in ESPECIALIDADES.items(): DEFS[k]=('D',v)
